# Generated by Django 4.0.3 on 2022-06-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_addproduct_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
