# Generated by Django 4.0.3 on 2022-06-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_addproduct_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='filepath'),
        ),
    ]
