# Generated by Django 4.0.3 on 2022-06-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cart_addproductid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='addproductid',
        ),
    ]
