# Generated by Django 4.0.3 on 2022-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_cart_addproductid'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
