# Generated by Django 4.0.3 on 2022-06-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profile_phone_number'),
        ('home', '0014_profile'),
    ]

    operations = [
    ]
